"""initial schema

Revision ID: 5f04d9df9438
Revises: 
Create Date: 2026-03-01 15:50:03.315510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f04d9df9438'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processos',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'ARQUIVADO', name='processostatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', name='uq_processo_nome')
    )
    op.create_index('idx_processo_created_at', 'processos', ['created_at'], unique=False)
    op.create_index('idx_processo_nome', 'processos', ['nome'], unique=False)
    op.create_index('idx_processo_status', 'processos', ['status'], unique=False)
    op.create_table('configuracoes',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('formato_saida', sa.Enum('ARQUIVO_UNICO', 'MULTIPLOS_ARQUIVOS', name='formatosaida'), nullable=False),
    sa.Column('output_dir', sa.String(length=500), nullable=False),
    sa.Column('agendamento_cron', sa.String(length=100), nullable=True),
    sa.Column('agendamento_tipo', sa.Enum('RECORRENTE', 'ONE_TIME', 'MANUAL', name='agendamentotipo'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_retries <= 10', name='ck_configuracao_retries_max'),
    sa.CheckConstraint('max_retries >= 0', name='ck_configuracao_retries_min'),
    sa.CheckConstraint('timeout <= 86400', name='ck_configuracao_timeout_max'),
    sa.CheckConstraint('timeout > 0', name='ck_configuracao_timeout_positive'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_configuracao_agendamento_tipo', 'configuracoes', ['agendamento_tipo'], unique=False)
    op.create_index('idx_configuracao_processo_id', 'configuracoes', ['processo_id'], unique=False)
    op.create_table('execucoes',
    sa.Column('processo_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('CRIADO', 'AGUARDANDO', 'EM_EXECUCAO', 'PAUSADO', 'CONCLUIDO', 'FALHOU', 'CANCELADO', 'CONCLUIDO_COM_ERROS', name='execucaostatus'), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paginas_processadas', sa.Integer(), nullable=False),
    sa.Column('bytes_extraidos', sa.BigInteger(), nullable=False),
    sa.Column('taxa_erro', sa.Float(), nullable=False),
    sa.Column('tentativa_atual', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('bytes_extraidos >= 0', name='ck_execucao_bytes_min'),
    sa.CheckConstraint('paginas_processadas >= 0', name='ck_execucao_paginas_min'),
    sa.CheckConstraint('taxa_erro <= 100.0', name='ck_execucao_taxa_erro_max'),
    sa.CheckConstraint('taxa_erro >= 0.0', name='ck_execucao_taxa_erro_min'),
    sa.CheckConstraint('tentativa_atual > 0', name='ck_execucao_tentativa_positive'),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execucao_created_at', 'execucoes', ['created_at'], unique=False)
    op.create_index('idx_execucao_processo_created', 'execucoes', ['processo_id', 'created_at'], unique=False)
    op.create_index('idx_execucao_processo_id', 'execucoes', ['processo_id'], unique=False)
    op.create_index('idx_execucao_status', 'execucoes', ['status'], unique=False)
    op.create_table('logs',
    sa.Column('execucao_id', sa.Uuid(), nullable=False),
    sa.Column('nivel', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='lognivel'), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_execucao_id', 'logs', ['execucao_id'], unique=False)
    op.create_index('idx_log_execucao_timestamp', 'logs', ['execucao_id', 'timestamp'], unique=False)
    op.create_index('idx_log_nivel', 'logs', ['nivel'], unique=False)
    op.create_index('idx_log_timestamp', 'logs', ['timestamp'], unique=False)
    op.create_table('paginas_extraidas',
    sa.Column('execucao_id', sa.Uuid(), nullable=False),
    sa.Column('url_original', sa.String(length=2048), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('SUCESSO', 'FALHOU', 'IGNORADO', name='paginastatus'), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('erro_mensagem', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('tamanho_bytes >= 0', name='ck_pagina_tamanho_min'),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pagina_execucao_id', 'paginas_extraidas', ['execucao_id'], unique=False)
    op.create_index('idx_pagina_execucao_status', 'paginas_extraidas', ['execucao_id', 'status'], unique=False)
    op.create_index('idx_pagina_status', 'paginas_extraidas', ['status'], unique=False)
    op.create_index('idx_pagina_url', 'paginas_extraidas', ['url_original'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pagina_url', table_name='paginas_extraidas')
    op.drop_index('idx_pagina_status', table_name='paginas_extraidas')
    op.drop_index('idx_pagina_execucao_status', table_name='paginas_extraidas')
    op.drop_index('idx_pagina_execucao_id', table_name='paginas_extraidas')
    op.drop_table('paginas_extraidas')
    op.drop_index('idx_log_timestamp', table_name='logs')
    op.drop_index('idx_log_nivel', table_name='logs')
    op.drop_index('idx_log_execucao_timestamp', table_name='logs')
    op.drop_index('idx_log_execucao_id', table_name='logs')
    op.drop_table('logs')
    op.drop_index('idx_execucao_status', table_name='execucoes')
    op.drop_index('idx_execucao_processo_id', table_name='execucoes')
    op.drop_index('idx_execucao_processo_created', table_name='execucoes')
    op.drop_index('idx_execucao_created_at', table_name='execucoes')
    op.drop_table('execucoes')
    op.drop_index('idx_configuracao_processo_id', table_name='configuracoes')
    op.drop_index('idx_configuracao_agendamento_tipo', table_name='configuracoes')
    op.drop_table('configuracoes')
    op.drop_index('idx_processo_status', table_name='processos')
    op.drop_index('idx_processo_nome', table_name='processos')
    op.drop_index('idx_processo_created_at', table_name='processos')
    op.drop_table('processos')
    # ### end Alembic commands ###
